import {SignInButton, SignedIn, SignedOut, UserButton, auth, useUser} from "@clerk/nextjs";
import {type NextPage} from "next";
import Head from "next/head";

import type {RouterOutputs} from "~/utils/api";
import {api} from "~/utils/api";

const CreatePostWizard = () => {
  const {user} = useUser();

  if (!user) return null;

  return (
    <div className="flex w-full gap-3">
      <UserButton
        appearance={{
          elements: {avatarBox: "h-14 w-14 rounded-full"},
        }}
      />
      <input className="grow bg-transparent outline-none" placeholder="Text some emojis!!" />
    </div>
  );
};

type PostWithUser = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const {post, author} = props;

  return (
    <div key={post.id} className="border-b border-slate-400 p-8">
      <img alt="profile" src={author.profileImageUrl} />
      {post.content}
    </div>
  );
};

const Home: NextPage = () => {
  const {data, isLoading} = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;
  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            <SignedIn>
              <CreatePostWizard />
            </SignedIn>
            <SignedOut>
              <SignInButton />
            </SignedOut>
          </div>
          <div>
            {[...data, ...data].map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
