import {SignInButton, SignOutButton, SignedIn, SignedOut, UserButton} from "@clerk/nextjs";
import {type NextPage} from "next";
import Head from "next/head";

import {api} from "~/utils/api";

const Home: NextPage = () => {
  const {data} = api.example.getAll.useQuery();

  console.log(data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta content="Generated by create-t3-app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <SignedIn>
          <UserButton afterSignOutUrl="/" />
          <SignOutButton />
        </SignedIn>
        <SignedOut>
          <SignInButton />
        </SignedOut>
        <div>
          {data?.map((post) => (
            <div key={post.id}>{post.content}</div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
